### ISSUE TITLE
运行topic run报错

### ISSUE THREAD

**Issue by Zonzely** [gaojiuli/toapi#100]
python版本是3.5 toapi版本0.2.2
```
toapi new api
cd api
toapi run
```
执行topic run时报错
```
➜  api toapi run
Traceback (most recent call last):
  File "/usr/local/bin/toapi", line 9, in <module>
    load_entry_point('toapi==0.2.2', 'console_scripts', 'toapi')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/toapi/cli.py", line 81, in run
    app = importlib.import_module('app', base_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/zz/code/python/toapi_project/api/app.py", line 7, in <module>
    api.register(Page)
  File "/usr/local/lib/python3.5/dist-packages/toapi/api.py", line 31, in register
    item.__pattern__ = re.compile(item.__base_url__ + item.Meta.route)
TypeError: Can't convert 'dict' object to str implicitly

```

item.__base_url__是str, item.Meta.route是字典

**Comment by gaojiuli** [comment]
你的toapi版本是多少呢

**Comment by Zonzely** [comment]
toapi版本 0.2.2 @gaojiuli

**Comment by gaojiuli** [comment]
请用正式版1.0.0

**Comment by Zonzely** [comment]
releases里面有1.0.0， pip源安装的toapi， 版本最高是0.2.2 @gaojiuli

**Comment by gaojiuli** [comment]
你应该使用了阿里云的镜像源，阿里云的问题．尝试使用下面的命令．

`pip install -U toapi -i https://pypi.douban.com/simple`

**Comment by Zonzely** [comment]
soga
