### ISSUE TITLE
python2.7安装报错

### ISSUE THREAD

**Issue by xiaomingdaily** [gaojiuli/toapi#117]
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from htmlparsing import Attr, Text
  File "/usr/local/lib/python2.7/dist-packages/htmlparsing-0.1.5-py2.7.egg/htmlparsing.py", line 21
    def __init__(self, text: str):
                           ^
SyntaxError: invalid syntax

**Comment by gaojiuli** [comment]
v2.0.0 only support python3.6+

**Comment by KurtPrice** [comment]
If it is only supported by 3.6+ can we resolve this issue?
