### ISSUE TITLE
Flask logging error

### ISSUE THREAD

**Issue by tmshv** [gaojiuli/toapi#124]
python 3.7
toapi 2.1.1

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    api = Api()
  File "/usr/local/lib/python3.7/site-packages/toapi/api.py", line 24, in __init__
    self.__init_server()
  File "/usr/local/lib/python3.7/site-packages/toapi/api.py", line 27, in __init_server
    self.app.logger.setLevel(logging.ERROR)
AttributeError: module 'flask.logging' has no attribute 'ERROR'
```

**Comment by nautical** [comment]
You need to change
`from flask import Flask, logging, request, jsonify`
to 
`import logging
from flask import Flask, request, jsonify`

**Comment by mknippen** [comment]
@gaojiuli thanks for the merge! Is there a way that we can bump the version number and send to PyPi? I have a env that I would love to use a production version for.

Thanks!
