### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dineshlt** [gaojiuli/toapi#128]
Hi,

If I have run this comment **toapi -v** I am getting the below issue.

Kindly check and give the needfull suggession

Thanks...

```
Traceback (most recent call last):
  File "/usr/local/bin/toapi", line 9, in <module>
    load_entry_point('toapi==2.1.2', 'console_scripts', 'toapi')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/toapi/__init__.py", line 1, in <module>
    from toapi.api import Api
  File "/usr/local/lib/python2.7/dist-packages/toapi/api.py", line 20
    def __init__(self, site: str = '', browser: str = None) -> None:
                           ^
SyntaxError: invalid syntax
```

**Comment by dineshlt** [comment]
Hi,

I have changed Python 2.7 into 3.6 this issue has been fixed
