### ISSUE TITLE
Problem: can't start the app

### ISSUE THREAD

**Issue by triangle959** [gaojiuli/toapi#132]
When I ran this example, I reported the following error
`2019/09/19 10:15:50 [Register] OK <Post: /posts /news?p=1> 
2019/09/19 10:15:50 [Register] OK <Post: /posts?page={page} /news?p={page}> 
2019/09/19 10:15:50 [Register] OK <Page: /posts /news?p=1> 
2019/09/19 10:15:50 [Register] OK <Page: /posts?page={page} /news?p={page}> 
2019/09/19 10:15:50 [Serving ] OK http://0.0.0.0:5001 
2019/09/19 10:15:50 [Serving ] FAIL Windows error 1 
2019/09/19 10:15:50 [Serving ] FAIL Traceback (most recent call last):
  File "D:\python\lib\site-packages\toapi\api.py", line 50, in run
    self.app.run(host, port, **options)
  File "D:\python\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "D:\python\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "D:\python\lib\site-packages\click\utils.py", line 260, in echo
    file.write(message)
  File "D:\python\lib\site-packages\click\_winconsole.py", line 180, in write
    return self._text_stream.write(x)
  File "D:\python\lib\site-packages\click\_winconsole.py", line 164, in write
    raise OSError(self._get_error_message(GetLastError()))
OSError: Windows error 1
`

toapi, version 2.1.0
Flask 1.0.2
Python 3.6.0

**Comment by elliotgao2** [comment]
Closing during a bulk cleanup of pre-2.2.x issues. The codebase has just been modernized (Python 3.10+, uv packaging, Flask 3, ruff, mocked test suite, rewritten docs — see 2.2.2 on PyPI), and this report predates that work. If something still affects you on 2.2.x please open a fresh issue with reproduction steps — happy to take a look. Thanks for the original report!
