### ISSUE TITLE
没怎么用过python

### ISSUE THREAD

**Issue by s749312025** [gaojiuli/toapi#7]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from toapi import XPath, Item, Api
  File "/Library/Python/2.7/site-packages/toapi/__init__.py", line 2, in <module>
    from toapi.item import *
  File "/Library/Python/2.7/site-packages/toapi/item.py", line 17
    class Item(metaclass=ItemType):
                        ^
SyntaxError: invalid syntax

**Comment by howie6879** [comment]
You are using python2.7, toapi only supports python3.5 +, maybe this https://github.com/gaojiuli/toapi/pull/6 will help you
